name: iamhere
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_dotenv: ^6.0.0

  dio: ^5.9.0
  json_annotation: ^4.9.0

  flutter_riverpod: ^3.0.3

  go_router: ^17.0.0

  kakao_flutter_sdk: ^1.9.7+3
  kakao_map_sdk: ^1.2.2
  flutter_screenutil: ^5.9.3
  permission_handler: ^12.0.1
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  riverpod_annotation: ^3.0.3
  riverpod_generator: ^3.0.3
  build_runner: ^2.4.9
  json_serializable: ^6.10.0
  coverage: ^1.15.0
  mockito: ^5.5.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - iam_here_flutter_secret.env

  fonts:
    - family: BMHANNAPro
      fonts:
        - asset: assets/fonts/BMHANNAPro.ttf
    - family: BMJUA
      fonts:
        - asset: assets/fonts/BMJUA_ttf.ttf
    - family: BMHANNAAir
      fonts:
        - asset: assets/fonts/BMHANNAAir_ttf.ttf
    - family: BMDOHYEON
      fonts:
        - asset: assets/fonts/BMDOHYEON_ttf.ttf